# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'YMBrowseIphone' do
pod 'CocoaHTTPServer', '~> 2.3'
end

target 'YMBrowseIphoneTests' do

end

